spring.application.name=foodiesapi

#mongoDB configuration
spring.data.mongodb.uri=mongodb+srv://singhakshatsolanki:singhpassword@cluster0.j6l3v.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=foodies

#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=ap-south-1
aws.s3.bucketname=foodies-foods-akkie

#Secret-Key
jwt.secret.key=jfyw5psd8ncnsyr29opwed9kdlefifud08479flmwodlwpsdi836==skeoi
